name: PR-Validation

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Executa a cada hora

jobs:
  build-on-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Github Action
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Restore dependencies
      run: dotnet restore **/*.csproj

    - name: Build the app
      run: dotnet build **/*.csproj --no-restore

    - name: Run custom script
      run: |
        echo "Running custom script on push..."
        # Adicione seu script personalizado aqui
        ./custom-script.sh

  scheduled-task:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Github Action
      uses: actions/checkout@v2

    - name: Run simple task
      run: |
        echo "Running scheduled task..."
        ls -la
